### ISSUE TITLE
why cause civetweb segment fault ?

### ISSUE THREAD

**Issue by xjzxd** [civetweb/civetweb#1178]
gdb core file export:
Program terminated with signal 11, Segmentation fault.
#0  0x00007f3cec84638c in free () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-157.el7.x86_64
(gdb) bt
#0  0x00007f3cec84638c in free () from /lib64/libc.so.6
#1  0x000000000049653d in ssl_cert_free ()
#2  0x00000000004a1236 in SSL_free ()
#3  0x000000000042ec2d in close_connection (conn=0x7f3ced0d4b80) at civetweb.c:18104
#4  0x0000000000431434 in process_new_connection (conn=0x7f3ced0d4b80) at civetweb.c:19745
#5  0x0000000000431b05 in worker_thread_run (conn=0x7f3ced0d4b80) at civetweb.c:20069
#6  0x0000000000431d6e in worker_thread (thread_func_param=0x7f3ced0d4b80) at civetweb.c:20161
#7  0x00007f3cecb8edc5 in start_thread () from /lib64/libpthread.so.0
#8  0x00007f3cec8bd73d in clone () from /lib64/libc.so.6

**Comment by bel2125** [comment]
Could you give some more information on the system:
What CivetWeb version or commit ID are you using?
What operating system?
Are you using it standalone or embedded in some executable?
Did you build it using the standard make file?
If so, could you run "civetweb -I" to get some information like this one:
```JSON
CivetWeb V1.17 (CivetWeb V1.17)
{
"version" : "1.17",
"os" : "Linux #1801-Microsoft Sat Sep 11 15:28:00 PST 2021 (4.4.0-18362-Microsoft) - x86_64",
"features" : 1610616831,
"feature_list" : "Server: Files HTTPS CGI IPv6 WebSockets Lua JavaScript Cache Stats",
"lua_version" : "502 (Lua 5.2.4)",
"javascript" : "Duktape 1.8.0",
"build" : "May  1 2023",
"compiler" : "gcc: 7.5.0",
"data_model" : "int:2/4/8/8, float:4/8/16, char:1/4, ptr:8, size:8, time:8"
}
```
I do not have this segfault in the version I am using.

What version of openssl or mbedtls are you using?

**Comment by hansipie** [comment]
Also ... which version of OpenSSL are you using ?

**Comment by xjzxd** [comment]
> Could you give some more information on the system: What CivetWeb version or commit ID are you using? What operating system? Are you using it standalone or embedded in some executable? Did you build it using the standard make file? If so, could you run "civetweb -I" to get some information like this one:
> 
> ```json
> CivetWeb V1.17 (CivetWeb V1.17)
> {
> "version" : "1.17",
> "os" : "Linux #1801-Microsoft Sat Sep 11 15:28:00 PST 2021 (4.4.0-18362-Microsoft) - x86_64",
> "features" : 1610616831,
> "feature_list" : "Server: Files HTTPS CGI IPv6 WebSockets Lua JavaScript Cache Stats",
> "lua_version" : "502 (Lua 5.2.4)",
> "javascript" : "Duktape 1.8.0",
> "build" : "May  1 2023",
> "compiler" : "gcc: 7.5.0",
> "data_model" : "int:2/4/8/8, float:4/8/16, char:1/4, ptr:8, size:8, time:8"
> }
> ```
> 
> I do not have this segfault in the version I am using.
>
 civetweb version is 1.17
 
> What version of openssl or mbedtls are you using?

openssl version is openssl-1.1.1u
