### ISSUE TITLE
asan stack-overflow

### ISSUE THREAD

**Issue by fm123456** [civetweb/civetweb#1259]
=================================================================
==8983==ERROR: AddressSanitizer: stack-overflow on address 0x7f9bf1ed9c20 (pc 0x0000006a56bf bp 0x7f9bf1eda480 sp 0x7f9bf1ed9c10 T34)
    #0 0x6a56bf in __interceptor_vsnprintf ../../../../gcc-13.2.0/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:1746
    #1 0x7f9c24bedfcf in alloc_vprintf /data/home/marvinfang/tgf_server/third_party/packages/civetweb-v1.16/src/civetweb.c:6957
    #2 0x7f9c24bfd731 in mg_vprintf /data/home/marvinfang/tgf_server/third_party/packages/civetweb-v1.16/src/civetweb.c:7024
    #3 0x7f9c24bfda9d in mg_printf /data/home/marvinfang/tgf_server/third_party/packages/civetweb-v1.16/src/civetweb.c:7042
    #4 0x7f9c24bfdcbd in send_http1_response_status_line /data/home/marvinfang/tgf_server/third_party/packages/civetweb-v1.16/src/response.inl:58
    #5 0x7f9c24bfdcbd in mg_response_header_send /data/home/marvinfang/tgf_server/third_party/packages/civetweb-v1.16/src/response.inl:305
    #6 0x7f9c24c03d00 in mg_send_http_error_impl /data/home/marvinfang/tgf_server/third_party/packages/civetweb-v1.16/src/civetweb.c:4545
    #7 0x7f9c24c042c5 in mg_send_http_error /data/home/marvinfang/tgf_server/third_party/packages/civetweb-v1.16/src/civetweb.c:4570
    #8 0x7f9c24c1af7e in handle_request /data/home/marvinfang/tgf_server/third_party/packages/civetweb-v1.16/src/civetweb.c:15139
    #9 0x7f9c24c1f427 in handle_request_stat_log /data/home/marvinfang/tgf_server/third_party/packages/civetweb-v1.16/src/civetweb.c:6571
    #10 0x7f9c24c1f427 in process_new_connection /data/home/marvinfang/tgf_server/third_party/packages/civetweb-v1.16/src/civetweb.c:19482
    #11 0x7f9c24c2104f in worker_thread_run /data/home/marvinfang/tgf_server/third_party/packages/civetweb-v1.16/src/civetweb.c:19858
    #12 0x7f9c24c2104f in worker_thread /data/home/marvinfang/tgf_server/third_party/packages/civetweb-v1.16/src/civetweb.c:19950
    #13 0x7f9c24ec1ea4 in start_thread (/lib64/libpthread.so.0+0x7ea4) (BuildId: e10cc8f2b932fc3daeda22f8dac5ebb969524e5b)
    #14 0x7f9c1f5059fc in clone (/lib64/libc.so.6+0xfe9fc) (BuildId: 3604f44eaf58b24c443806eaa831876c1f096f6e)

SUMMARY: AddressSanitizer: stack-overflow ../../../../gcc-13.2.0/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:1746 in __interceptor_vsnprintf
Thread T34 (civetweb-worker) created by T0 here:
    #0 0x65c096 in __interceptor_pthread_create ../../../../gcc-13.2.0/libsanitizer/asan/asan_interceptors.cpp:208
    #1 0x7f9c24bebd91 in mg_start_thread_with_id /data/home/marvinfang/tgf_server/third_party/packages/civetweb-v1.16/src/civetweb.c:5748

==8983==ABORTING

How should I solve this problem?

**Comment by bel2125** [comment]
I guess this is a Linux family operating system.
How did you set the stack size?
-) as system default
-) in the `USE_STACK_SIZE` compile time setting

What *exact* version is this? Here line 6957 is not in `alloc_vprintf`
https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L6957

**Comment by bel2125** [comment]
My assumption: In this system, a very small stack size has been set - maybe 20k or even less.
Then the solution is to set a higher stack size in the system.

**Comment by fm123456** [comment]
thinks，We set USE_STACK_SIZE to 512k, and then this issue did not appear again
